# Generated by Django 4.0.4 on 2022-05-26 20:18

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the manufacturer', max_length=45, unique=True)),
                ('city', models.CharField(blank=True, help_text='City in which the manufacturer is based', max_length=45, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, help_text='Country in which the manufacturer is based', max_length=2, null=True)),
                ('link', models.URLField(blank=True, help_text='Link to the manufacturers main website', max_length=45, null=True)),
                ('founded', models.PositiveIntegerField(blank=True, help_text='Year in which the manufacturer was founded', null=True)),
                ('dissolved', models.PositiveIntegerField(blank=True, help_text='Year in which the manufacturer was dissolved', null=True)),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
            ],
        ),
    ]
